### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by anse3832** [csjliang/LDL#3]
when I tried to train LDL using train_Realworld_LDL.yml, it shows an error below

Traceback (most recent call last):
  File "./basicsr/train.py", line 212, in <module>
    train_pipeline(root_path)
  File "./basicsr/train.py", line 121, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "./basicsr/train.py", line 39, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "/nas/workspace/anse/code/pytorch/SR/LDL/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/nas/workspace/anse/code/pytorch/SR/LDL/basicsr/utils/registry.py", line 65, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'RealESRGANDataset' found in 'dataset' registry!"

**Comment by csjliang** [comment]
Hi,

Please make sure that you run the `realesrgan/train.py` file instead of `basicsr/train.py`. Thanks.

**Comment by anse3832** [comment]
Thanks! It seems work well.
